language: node_js
node_js:
  - '8'
script:
  - npm run build
before_deploy:
  - ./split_app.sh firebase
  - ./split_app.sh dropbox
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
- provider: firebase
  token: "$FIREBASE_TOKEN"